---
title: "Course support"
---

Most of you will need help at some point, and we want to make sure you can identify where that is so that you don't get too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during the lecture or lab, feel free to ask it!
There are likely other students with the same question, so asking will create a learning opportunity for everyone.

## Help from humans

### Office hours

The teaching team is here to help you be successful in the course.
You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments.
Many questions are most effectively answered in person, so office hours are a valuable resource.
I encourage each and every one of you to take advantage of this resource!
Make a pledge to stop by during office hours at least once during the first three weeks of class.
If you have no questions, stop by and say hi and introduce yourself.
You can find a list of everyone's office hours [here](/course-team.html).

My office hours will start in Week 1, TA office hours will start in Week 2.

### Ed Discussion

Have a question that can't wait for office hours?
Prefer to write out your question in detail rather than asking in person?
The course discussion forum, Ed Discussion, is the best venue for these!
There is a chance another student has already asked a similar question, so please check the other posts on before asking a new question.
If you know the answer to a question that is posted, I encourage you to respond!

You can access this tool on the course website toolbar -- just click on the lifesaver icon.

### Peer tutoring

MINT Peer Tutoring (Meaningful Interactive Tutoring) are small groups of 2-5 students in the same course who meet weekly with a Peer Tutor.
This semester, Peer Tutor who will be leading MINT Peer Tutoring for STA 199 is Stanley Borden ([stanley.borden\@duke.edu](mailto:stanley.borden@duke.edu)).

The peer tutoring groups are a resource focused on allowing students to receive additional support for questions they have on the course content while still being part of a community of fellow learners.
Peer tutors communicate with students in advance of the meetings so that they can be responsive to student needs during the group meetings.
Some groups meet in person and some meet virtually.

-   In person, Wednesday 7:00 pm
-   Virtual, Wednesday 8:05 pm

For more details and to see what other courses we offer services for, please visit their website: <https://arc.duke.edu/peer-education>

Signups for MINT Peer Tutoring open the morning of Thursday, September 5th and groups start meeting on Monday, September 9th.

Note that peer tutors are not directly affiliated with the course, however they tend to be students who have taken the course in the past.

## Help from AI: Chatbot

The course has a chatbot that has been trained specifically on the course textbooks.
If you're looking for AI-help, we strongly recommend starting here.

You can access this tool on the course website toolbar -- just click on the lifesaver icon.

## Email

Please refrain from emailing any course content questions (those should go to Ed Discussion), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.).
For such matters, you may email Dr. Mine Çetinkaya-Rundel at [mc301\@duke.edu](mailto:mc301@duke.edu).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly.
**If you email me, please include "STA 199" in the subject line.** Barring extenuating circumstances, I will respond to STA 199 emails within 48 hours Monday - Friday.
Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

There are times you may need help with the class that is beyond what can be provided by the teaching team.
In those instances, I encourage you to visit the Academic Resource Center.
The [Academic Resource Center (ARC)](https://arc.duke.edu) offers free services to all students during their undergraduate careers at Duke.
Services include Learning Consultations, Peer Tutoring and Study Groups, ADHD/LD Coaching, Outreach Workshops, and more.
Because learning is a process unique to every individual, they work with each student to discover and develop their own academic strategy for success at Duke.
Contact the ARC to schedule an appointment.
Undergraduates in any year, studying any discipline can benefit!
Contact [ARC\@duke.edu](mailto:arc@duke.edu), 919-684-5917.

## Mental health and well-being

Duke is committed to holistic student well-being, including mental, emotional, and physical health.
The university offers resources to help students manage daily stress, encourage intentional self-care, and access just-in-time support.
If you find you need support, your mental and/or emotional health concerns are impacting your day-to-day activities and your academic performance, or you need someone to talk to, the resources below are available to you:

-   [**DukeReach**](https://students.duke.edu/wellness/dukereach/)**:** DukeReach provides comprehensive outreach services to support students in managing all aspects of well-being, including referrals and follow-up services for students who are experiencing significant challenges related to mental health, physical health, social adjustment, and/or a variety of other stressors. You can reach the DukeReach team at [dukereach\@duke.edu](mailto:dukereach@duke.edu).
-   [**Counseling and Psychological Services (CAPS)**](https://students.duke.edu/wellness/caps/)**:** CAPS services include individual and group counseling services, psychiatric services, and workshops. CAPS also provides referrals to off-campus resources for specialized care. You can reach CAPS at (919) 660-1000.
-   [**TimelyCare**](https://Timelycare.com/bluedevils)[^1]**:** TimelyCare is an online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling.
-   [**BC Fellows for Healthy Relationship**](https://students.duke.edu/wellness/duwell/sexualhealth/balthrop-cassidy-fellowship/)**:** The BC Fellows meet with students individually and in groups, supporting the development of healthy relationships and building meaningful community in all areas of a student’s life.
-   [**DukeLine**](https://sites.duke.edu/dukeline/)**:** Students who want to connect anonymously with a Peer Coach can text 984-230-4888 from 5 to 11 p.m. daily. DukeLine offers in-the-moment anonymous, non-emergency text support from a peer.
-   [**DuWell**](https://students.duke.edu/wellness/duwell/)**:** DuWell provides Moments of Mindfulness (stress management and resilience building) and meditation programming (Koru workshop) to assist students in developing a daily emotional well-being practice. All are welcome, and no experience is necessary. You can reach DuWell at (919) 681-8421.

[^1]: Formerly known as Blue Devils Care.

## Course costs

-   **Textbooks:** The textbooks for this course are freely available on the web.
-   **Laptops:** Each student is expected to have a laptop they can bring to each lecture and lab.

If you are having difficulty with the costs associated with this course, here are some resources:

-   [**Karsh Office of Undergraduate Support**](https://financialaid.duke.edu/)**:** Regardless of your aid package, Karsh offers loans and resources for connecting students with campus programs that might help alleviate course costs.

-   [**DukeLIFE**](https://dukelife.duke.edu/programs/course-materials-assistance/)**:** The Course Material Assistance program offers assistance for eligible students, including through the [LIFE Loaner Laptop Program](https://dukelife.duke.edu/academic-support/loaner-laptop-program/).
    Students who are eligible for DukeLIFE benefits are notified before the start of the semester; program resources are limited.

-   [**Duke Libraries**](https://library.duke.edu/course-support/course-reserves/textbooks)**:** The library’s Top Textbook Program allows you to rent some textbooks for 3 hours at a time.

-   [**Duke Link**](https://link.duke.edu/)**:** You can reserve rental equipment from the Link for course-specific technology needs, such as a Digital Voice Recorder, HD Video Camera, TI-84 Plus CE, DSLR camera kit, Tripod, Shotgun Mic, iPad Mini 4, Handheld Projector, or GoPro.

## Assistance with Zoom or Canvas

For technical help with Canvas or Zoom, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).
You can also access the self-service help documentation for Zoom and Canvas.

Note that we will be using Canvas minimally in this course (primarily for announcements and the grade book).
All assignment submissions will take place on Gradescope and GitHub, and conversations will take place on Ed Discussion.

Zoom will be used for online office hours and as a backup option should we need to hold the course online instead of in person.
