---
title: "Communicating data science results with Quarto"
subtitle: "Lecture 24"
date: "2024-11-26"
format: 
  live-revealjs: 
    output-file: 24-communicate-quarto-slides.html
---

<!-- begin: webr fodder -->

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

```{webr}
#| edit: false
#| echo: false
#| output: false
options(width = 60)
```

<!-- end: webr fodder -->

<!-- begin: ae definition -->

```{r}
#| include: false
todays_ae <- "ae-19-equality-randomization"
```

<!-- end: ae definition -->

# Warm-up

## Announcements

-   Lab 8 due tonight at 10:30 pm

# From last time

## `ae-19-equality-randomization`

::: appex
-   Go to your ae project in RStudio.

-   Continue working on `ae-19-equality-randomization.qmd`.
:::

## Recap of AE {.smaller}

-   A hypothesis test is a statistical technique used to evaluate competing claims (null and alternative hypotheses) using data.
-   We simulate a null distribution using our original data.
-   We use our sample statistic and direction of the alternative hypothesis to calculate the p-value.
-   We use the p-value to determine conclusions about the alternative hypotheses.

# Projects with Quarto

## Your project write-up with Quarto {.smaller}

-   Figure sizing: `fig-width`, `fig-height`, etc. in code cells.

-   Figure layout: `layout-ncol` for placing multiple figures in a chunk.

-   Further control over figure layout with the **patchwork** package.

-   Cell options for what makes it in your final report: `message`, `echo`, etc.

-   Citations.

-   Finalizing your report with `echo: false`.

## Building your project website with Quarto

-   The `docs` folder.

-   Making sure your website reflects your latest changes.

-   Customizing the look of your website.

## Slides

-   **Option 1:** Make your slides not in Quarto but make sure they’re available in your Quarto project website.

-   **Option 2:** Make your slides with Quarto.
