---
title: "Improvement and progress"
subtitle: "Milestone 3"
categories: "Project"
execute:
  echo: false
---

By this point you've received feedback on your proposal and you should be working on incorporating that feedback to improve your project and making further progress on it.
This milestone ensures you're keeping on task and doing these things.

# Goals

The goals of this milestone are as follows:

-   Incorporate feedback from your proposal
-   Make progress on your project prior to the peer review

# Instructions

Make some progress, evidenced by commits to your repo since project milestone 2. 
These commits should

-   explicitly closing issues opened as proposal feedback, and
-   make further progress on the project.

# Grading

This milestone will be graded for completion, not accuracy.
We will check to see if the team has made commits to their repo since project milestone 2 and closed all issues that were opened as part of proposal feedback.

-   0 points: No commits since project milestone 2

-   1 point: Only a single commit since project milestone 2, regardless of how many issues closed

-   2-4 points: More than 1 commit since project milestone 2 and but not all issues closed

-   5 points: More than 1 commit since project milestone 2 and all issues closed

::: callout-note
There won't be a lab session dedicated to this milestone.
You are to work with your team outside of class time to complete this task.
:::
