---
title: "AE 00: UN Votes"
format: 
  live-html:
    code-link: true
    mainfont: Atkinson Hyperlegible
engine: knitr
webr:
  packages:
    - tidyverse
    - scales
    - DT
    - unvotes
    - ggthemes
  cell-options:
    autorun: false
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Introduction

How do various countries vote in the United Nations General Assembly, how have their voting patterns evolved throughout time, and how similarly or differently do they view certain issues?
Answering these questions (at a high level) is the focus of this analysis.

### Packages

We will use the **tidyverse**, **lubridate**, and **scales** packages for data wrangling and visualization, and the **DT** package for interactive display of tabular output, and the **unvotes** package for the data.

```{webr}
#| label: load-packages
library(tidyverse)
library(scales)
library(unvotes)
library(DT)
library(ggthemes)
```

### Data

The data we're using originally come from the **unvotes** package.
In the chunk below we modify the data by joining the various data frames provided in the package to help you get started with the analysis.

```{webr}
unvotes <- un_votes |>
  inner_join(un_roll_calls, by = "rcid") |>
  inner_join(
    un_roll_call_issues, 
    by = join_by(rcid == rcid), 
    relationship = "many-to-many"
  )
head(unvotes)
```

## UN voting patterns

Let's create a data visualisation that displays how the voting record of the United States, United Kingdom, and Turkey changed over time.

```{webr}
#| label: plot-yearly-yes-issue
#| warning: false
#| fig-width: 10
#| fig-height: 6
unvotes |>
  filter(country %in% c("United Kingdom", "United States", "Turkey")) |>
  mutate(year = year(date)) |>
  group_by(country, year, issue) |>
  summarize(percent_yes = mean(vote == "yes"), .groups = "drop") |>
  ggplot(mapping = aes(x = year, y = percent_yes, color = country)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap(~issue) +
  scale_y_continuous(labels = percent) +
  scale_color_colorblind() +
  labs(
    title = "Percentage of 'Yes' votes in the UN General Assembly",
    subtitle = "1946 to 2019",
    y = "% Yes",
    x = "Year",
    color = "Country"
  )
```

::: {style="border-left:3px solid #BCF4F5; padding: 0.5em;background: #BCF4F550;"}
**Task:** Write your first piece of (R) code! 

---

Modify the code cell above to change the plot to include a different country in place of Turkey.
Note that the country name should be spelled and capitalized exactly the same way as it appears in the data.
See the [Appendix](#appendix) for a list of the countries in the data.
:::

## References

1.  Robinson D (2021). _unvotes: United Nations General Assembly Voting Data_. R package version 0.3.0, <https://github.com/dgrtwo/unvotes>.
2.  Erik Voeten "Data and Analyses of Voting in the UN General Assembly" Routledge Handbook of International Organization, edited by Bob Reinalda (published May 27, 2013).
3.  Much of the analysis has been modeled on the examples presented in the [unvotes package vignette](https://cran.r-project.org/web/packages/unvotes/vignettes/unvotes.html).

## Appendix {#appendix}

Below is a list of countries in the dataset:

```{r}
#| label: list-countries
#| edit: false
#| echo: false
unvotes::un_votes |> 
  dplyr::select(country) |>
  dplyr::distinct(country) |>
  dplyr::arrange(country) |> 
  DT::datatable()
```
